### ISSUE TITLE
Unable to import legacy CommonJS module

### ISSUE THREAD

**Issue by dotansimha** [rollup/rollup-plugin-commonjs#129]
Hi,

I am using Ionic 2, and it uses rollup with rollup-plugin-commonjs, and I would like to load into the bundle an old CommonJS package, called `meteor-client-side`. 
This package is a bundle that cannot be modified in any way, and the most of it's work is to patch `window` and the Global scope. 

When trying import it as follow:
```
import 'meteor-client-side';
```

or:
```
import 'meteor-client-side/dist/meteor-client-side.bundle.js';
```

The package has "main" defined in it's package.json.

All I get is:
```
[16:38:21]  Error: Illegal reassignment to import 'commonjsHelpers'
    at error (/Users/dotansimha/Dev/whatsapp-ionic-cli/node_modules/rollup/dist/rollup.js:5404:12)
    at disallowIllegalReassignment (/Users/dotansimha/Dev/whatsapp-ionic-cli/node_modules/rollup/dist/rollup.js:5422:4)
    at AssignmentExpression.bind (/Users/dotansimha/Dev/whatsapp-ionic-cli/node_modules/rollup/dist/rollup.js:5496:3)
    at /Users/dotansimha/Dev/whatsapp-ionic-cli/node_modules/rollup/dist/rollup.js:5149:50
    at ExpressionStatement.eachChild (/Users/dotansimha/Dev/whatsapp-ionic-cli/node_modules/rollup/dist/rollup.js:5166:5)
    at ExpressionStatement.bind (/Users/dotansimha/Dev/whatsapp-ionic-cli/node_modules/rollup/dist/rollup.js:5149:7)
    at BlockStatement.bind (/Users/dotansimha/Dev/whatsapp-ionic-cli/node_modules/rollup/dist/rollup.js:5619:9)
    at FunctionExpression.bind (/Users/dotansimha/Dev/whatsapp-ionic-cli/node_modules/rollup/dist/rollup.js:6470:13)
    at /Users/dotansimha/Dev/whatsapp-ionic-cli/node_modules/rollup/dist/rollup.js:5149:50
    at CallExpression.eachChild (/Users/dotansimha/Dev/whatsapp-ionic-cli/node_modules/rollup/dist/rollup.js:5163:19)
```

When trying to include those files under the rollup.config plugins (commonjs({ include: ... })) - it still the same.

Any idea?

Thanks

**Comment by mmazloum** [comment]
@dotansimha I get the same error event with ionic2-app-script@beta using webpack, did you manage to make something work between latest ionc2 release and Meteor since you posted this issue ? To check their latest info on release http://blog.ionic.io/ionic-2-rc-weekend-updates/

**Comment by dotansimha** [comment]
@mmazloum 
I did another thing instead - used the Meteor CLI and not the Ionic CLI, and added Ionic manually to the Meteor project. 
You can find an example here: https://github.com/Urigo/Ionic2-MeteorCLI-WhatsApp

I think in the next version, Ionic will allow custom build with Webpack and not only with Rollup, so it might solve this issue. 

Closing this issue at the moment since I don't think that rollup-plugin-commonjs has anything to solve...

**Comment by mmazloum** [comment]
great i'll try this one ;-)
