### ISSUE TITLE
Dependency Resolving

### ISSUE THREAD

**Issue by seanoshea** [rollup/rollup-plugin-commonjs#210]
First of all, thanks for putting the time and effort into this library. I'm just getting back into JavaScript after a few years of focusing on mobile development and it's fantastic to see the JS tooling landscape change so much. I _think_ the following could be an issue with `rollup-plugin-commonjs`.

I'm running into an issue with rollup where I'm trying to expose an API client to a browser which includes `request-promise` functionality. https://github.com/seanoshea/fuzzymatchingjs/pull/2 is a PR which probably best describes the issue I'm encountering.

My rollup config looks like https://github.com/seanoshea/fuzzymatchingjs/pull/2/files#diff-5897c6a02fa80165006092c7c4c1dfe9.

But when I run the build, I get the following error:

 FAIL  test/clientside.test.js
  ● Test suite failed to run

    Cannot find module './_freeGlobal' from 'fuzzymatching.min.js'
      
      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:179:17)
      at dist/fuzzymatching.min.js:40:88677
      at Object.<anonymous>.e.exports (dist/fuzzymatching.min.js:16:131)
      at Object.<anonymous> (dist/fuzzymatching.min.js:16:261)

The full build output is:
```
bos-mac-soshea:fuzzymatchingjs sean.oshea$ npm run test

> fuzzymatchingjs@0.2.1 pretest /Users/sean.oshea/github/fuzzymatchingjs
> npm run lint && npm run build


> fuzzymatchingjs@0.2.1 lint /Users/sean.oshea/github/fuzzymatchingjs
> eslint src/lib/*.js test


/Users/sean.oshea/github/fuzzymatchingjs/src/lib/fuzzymatching.js
  6:5  warning  Unexpected console statement  no-console

✖ 1 problem (0 errors, 1 warning)


> fuzzymatchingjs@0.2.1 build /Users/sean.oshea/github/fuzzymatchingjs
> npm run build:browser && npm run build:node


> fuzzymatchingjs@0.2.1 build:browser /Users/sean.oshea/github/fuzzymatchingjs
> babel-node build-browser && npm run minify

node_modules/request-promise/node_modules/bluebird/js/browser/bluebird.js (5143:16) Use of eval is strongly discouraged, as it poses security risks and may cause issues with minification
commonjs-proxy:/Users/sean.oshea/github/fuzzymatchingjs/node_modules/lodash/_root.js (1:128) 'default' is not exported by 'node_modules/lodash/_root.js'
commonjs-proxy:/Users/sean.oshea/github/fuzzymatchingjs/node_modules/lodash/isObject.js (1:140) 'default' is not exported by 'node_modules/lodash/isObject.js'
commonjs-proxy:/Users/sean.oshea/github/fuzzymatchingjs/node_modules/lodash/isObjectLike.js (1:156) 'default' is not exported by 'node_modules/lodash/isObjectLike.js'
commonjs-proxy:/Users/sean.oshea/github/fuzzymatchingjs/node_modules/request-promise/node_modules/bluebird/js/browser/bluebird.js (1:182) 'default' is not exported by 'node_modules/request-promise/node_modules/bluebird/js/browser/bluebird.js'
commonjs-proxy:/Users/sean.oshea/github/fuzzymatchingjs/node_modules/request/index.js (1:129) 'default' is not exported by 'node_modules/request/index.js'
commonjs-proxy:/Users/sean.oshea/github/fuzzymatchingjs/node_modules/tough-cookie/lib/cookie.js (1:142) 'default' is not exported by 'node_modules/tough-cookie/lib/cookie.js'

> fuzzymatchingjs@0.2.1 minify /Users/sean.oshea/github/fuzzymatchingjs
> uglifyjs dist/fuzzymatching.js -o dist/fuzzymatching.min.js  --compress --mangle --comments '/Copyright/'


> fuzzymatchingjs@0.2.1 build:node /Users/sean.oshea/github/fuzzymatchingjs
> babel src -d . --presets es2015 --plugins add-module-exports

src/index.js -> index.js
src/lib/fuzzymatching.js -> lib/fuzzymatching.js

> fuzzymatchingjs@0.2.1 test /Users/sean.oshea/github/fuzzymatchingjs
> jest --coverage --coveragePathIgnorePatterns dist/*.min.js

 PASS  test/confidenceScore.test.js
 PASS  test/sortArray.test.js
 PASS  test/exports.test.js
 PASS  test/fuzzyMatchPattern.test.js
 FAIL  test/clientside.test.js
  ● Test suite failed to run

    Cannot find module './_freeGlobal' from 'fuzzymatching.min.js'
      
      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:179:17)
      at dist/fuzzymatching.min.js:40:88677
      at Object.<anonymous>.e.exports (dist/fuzzymatching.min.js:16:131)
      at Object.<anonymous> (dist/fuzzymatching.min.js:16:261)

Test Suites: 1 failed, 4 passed, 5 total
Tests:       16 passed, 16 total
Snapshots:   0 total
Time:        3.654s
Ran all test suites.
---------------------|----------|----------|----------|----------|----------------|
File                 |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
---------------------|----------|----------|----------|----------|----------------|
All files            |    97.37 |    79.76 |      100 |    97.37 |                |
 fuzzymatchingjs     |      100 |       75 |      100 |      100 |                |
  index.js           |      100 |       75 |      100 |      100 |             12 |
 fuzzymatchingjs/lib |     97.2 |       80 |      100 |     97.2 |                |
  fuzzymatching.js   |     97.2 |       80 |      100 |     97.2 |       16,32,75 |
---------------------|----------|----------|----------|----------|----------------|

npm ERR! Darwin 16.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "test"
npm ERR! node v6.10.2
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! fuzzymatchingjs@0.2.1 test: `jest --coverage --coveragePathIgnorePatterns dist/*.min.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the fuzzymatchingjs@0.2.1 test script 'jest --coverage --coveragePathIgnorePatterns dist/*.min.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the fuzzymatchingjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     jest --coverage --coveragePathIgnorePatterns dist/*.min.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs fuzzymatchingjs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls fuzzymatchingjs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/sean.oshea/.npm/_logs/2017-07-17T12_55_05_524Z-debug.log
bos-mac-soshea:fuzzymatchingjs sean.oshea$ 
```

The generated code in question looks like (https://github.com/seanoshea/fuzzymatchingjs/pull/2/files#diff-0754a6b177169535d6c346fefed8af06):

```
var freeGlobal = require('./_freeGlobal');

/** Detect free variable `self`. */
var freeSelf = (typeof self === 'undefined' ? 'undefined' : _typeof(self)) == 'object' && self && self.Object === Object && self;

/** Used as a reference to the global object. */
var root = freeGlobal || freeSelf || Function('return this')();

module.exports = root;
```

`_freeGlobal` appears to be imported at https://github.com/lodash/lodash/blob/master/.internal/nodeUtil.js#L1. It looks like `lodash` is a dependency of Bluebird (https://github.com/request/promise-core/blob/master/package.json#L36).

If I try to add `lodash` to the `fuzzymatchingjs`'s dependencies directly, this `require` for `freeGlobal` is resolved and the JavaScript is usable in a browser context.

Should `rollup-plugin-commonjs` be able to understand how to resolve the `freeGlobal` `require` statement?

**Comment by adnan1naeem** [comment]
I am facing same issue  any one found any solution rearding it?

**Comment by Ruplahlava** [comment]
Same here, anyone?

**Comment by TrySound** [comment]
@Ruplahlava Show your config

**Comment by Ruplahlava** [comment]
@TrySound  Ha, just was writing the solution!
I did not know that order in rollup plugins matter. Fixed by putting rollup-commonjs plugin just after rollup-plugin-node-resolve plugin and it is working like a charm! :)
