### ISSUE TITLE
CommonJs Plugin is missing on Rollup BundleOptions

### ISSUE THREAD

**Issue by msusur** [rollup/rollup-plugin-commonjs#227]
Today I was trying to use `ng-packagr` on a project where we used `angular2-moment`. After I ran the `> ng-packagr -p ng-package.json` command, I had the following error.  I have a proposal to fix this issue, and will attach a PR to this issue.

```
BUILD ERROR
'MomentModule' is not exported by node_modules/angular2-moment/index.js
Error: 'MomentModule' is not exported by node_modules/angular2-moment/index.js
    at error (/Users/my-app/node_modules/rollup/dist/rollup.js:185:14)
    at Module.error (/Users/my-app/node_modules/rollup/dist/rollup.js:8170:3)
    at Module.trace (/Users/my-app/node_modules/rollup/dist/rollup.js:8263:10)
    at ModuleScope.findDeclaration (/Users/my-app/node_modules/rollup/dist/rollup.js:7871:22)
    at Node.bind (/Users/my-app/node_modules/rollup/dist/rollup.js:6873:34)
    at eachChild.child (/Users/my-app/node_modules/rollup/dist/rollup.js:5674:34)
    at value.forEach.child (/Users/my-app/node_modules/rollup/dist/rollup.js:5683:38)
    at Array.forEach (native)
    at keys.forEach.key (/Users/my-app/node_modules/rollup/dist/rollup.js:5683:11)
    at Array.forEach (native)
```

And also here's my `ng-package.json` file.
```json
{
  "$schema": "./node_modules/ng-packagr/ng-package.schema.json",
  "lib": {
    "entryFile": "src/public_api.ts",
    "externals": {
      "angular2-moment": "angular2-moment/module"
    }
  }
}
```

**Comment by Rich-Harris** [comment]
Is this a rollup-plugin-commonjs issue or an ng-packagr issue? Is there anything that rollup-plugin-commonjs needs to do differently?
