### ISSUE TITLE
Cannot read property 'override' of undefined

### ISSUE THREAD

**Issue by Maxim-Chugaev** [rollup/rollup-plugin-commonjs#252]
I have error for some modules in node_modules.
.babelrc
```json
{
  "presets": [
    [
      "es2015",
      {
        "modules": false
      }
    ],
    "stage-1"
  ],
  "plugins": ["external-helpers"]
}
```
rollup.config.js
```javascript
import babel from 'rollup-plugin-babel';
import commonjs from 'rollup-plugin-commonjs';
import resolve from 'rollup-plugin-node-resolve';

export default {
  input: 'app.js',
  output: 'app.dist.js',
  plugins: [
    resolve(),
    babel({
      exclude: 'node_modules/**'
    }),
    commonjs()
  ]
};
```
error
```
app.js → stdout...
[!] (commonjs plugin) TypeError: Cannot read property 'override' of undefined in /Users/maksim/Documents/rotator/node_modules/express/node_modules/body-parser/index.js
node_modules/express/node_modules/body-parser/index.js
TypeError: Cannot read property 'override' of undefined in /Users/maksim/Documents/rotator/node_modules/express/node_modules/body-parser/index.js
    at error (/Users/maksim/Documents/rotator/node_modules/rollup/dist/rollup.js:185:14)
    at Promise.resolve.then.catch.err (/Users/maksim/Documents/rotator/node_modules/rollup/dist/rollup.js:9448:6)
    at <anonymous>
```

**Comment by Maxim-Chugaev** [comment]
please update acorn
https://github.com/ternjs/acorn/issues/608

**Comment by lukastaegert** [comment]
Thanks @Maxim-Chugaev for the hint, I have raised the minimal acorn version to 5.2.1 in rollup-plugin-commonjs@8.2.6. Please re-open this issue if you still experience this problem after updating.
