### ISSUE TITLE
CANNOT_IMPORT_SELF with rollup+commonjs+babel 

### ISSUE THREAD

**Issue by digitalkaoz** [rollup/rollup-plugin-commonjs#257]
This is a clone of https://github.com/rollup/rollup/issues/1730

Hey,

im getting the Error when Babel polyfills my code:

**error** 

```js
{ Error: A module cannot import itself
    at error (app/node_modules/rollup/dist/rollup.js:185:14)
    at Module.error (app/node_modules/rollup/dist/rollup.js:14293:3)
    at then.resolvedId (app/node_modules/rollup/dist/rollup.js:16054:15)
    at <anonymous>
  code: 'CANNOT_IMPORT_SELF',
  pos: 45,
  loc: 
   { file: '/app/node_modules/core-js/modules/es6.regexp.split.js',
     line: 2,
     column: 0 },
  frame: '1: import "core-js/modules/es6.regexp.replace";\n2: import "core-js/modules/es6.regexp.split";\n   ^\n3: import \'./_fix-re-wks\';\n4: import \'./_is-regexp\';' }
```

here the readable part:

```
[!] Error: A module cannot import itself
node_modules/core-js/modules/es6.regexp.split.js (2:0)
1: import "core-js/modules/es6.regexp.replace";
2: import "core-js/modules/es6.regexp.split";
   ^
3: import './_fix-re-wks';
4: import './_is-regexp';
```

**here is a simple reproducable case**:

```js
//entry.js
'a-b-c'.split(/-/);
```

```js
//.babelrc.js
module.exports = {
  plugins: ["@babel/plugin-external-helpers"],
  presets: [
    [
      "@babel/preset-env",
      {
        debug: true,
        modules: false,
        useBuiltIns: "usage",
        targets: {
          browsers: ["last 2 major versions"]
        }
      }
    ]
  ]
};
```

```js
//rollup.config.js
import uglify from "rollup-plugin-uglify";
import resolve from "rollup-plugin-node-resolve";
import commonjs from "rollup-plugin-commonjs";
import babel from "rollup-plugin-babel";

export default {
  input: "index.js",
  treeshake: false,
  plugins: [resolve(), commonjs(), babel(), uglify()],
  output: {
    file: "output.js",
    format: "iife",
    name: "example",
    sourcemap: true
  }
};
```

i've seen this error was raised by [angular2](https://github.com/angular/angular/issues/17389) and a few other projects, they solved it themselves (in userland code), but why is rollup complaining and not simply taking the module it already have?

**Comment by digitalkaoz** [comment]
something seems weird:

```
[node_modules/core-js/modules/es6.regexp.split.js] Added following polyfills:
  es6.regexp.split { "android":"56", "edge":"15", "ie":"10" }
  es6.regexp.replace { "android":"56", "edge":"15", "ie":"10" }
```

so a polyfill added itself as polyfill? this might be the problem?!

**Comment by lukastaegert** [comment]
Yes, it might be possible to teach rollup to handle self-imports properly. I plan on refactoring (or at least understanding 🙄) the circular dependency handling at some point in the future as there are some other issues revolving around this. This would be a good chance to revisit this behaviour as well. Thanks for bringing this up!

**Comment by digitalkaoz** [comment]
would love to help, but i think my understanding of this is far less deep than yours...ping me if i can help

**Comment by digitalkaoz** [comment]
with the latest version it seems to be fixed, thanks @lukastaegert for your awesome work!
