### ISSUE TITLE
[!] Error: Cannot split a chunk that has already been edited (0:124 – "graphql['default']")

### ISSUE THREAD

**Issue by gaberudy** [rollup/rollup-plugin-commonjs#308]
I get the following callback in rollup:
```
[!] Error: Cannot split a chunk that has already been edited (0:124 – "graphql['default']")
Error: Cannot split a chunk that has already been edited (0:124 – "graphql['default']")
    at MagicString$1._splitChunk (/Users/grudy/dev/stable/jsapp/node_modules/rollup/dist/rollup.js:6914:10)
    at MagicString$1._split (/Users/grudy/dev/stable/jsapp/node_modules/rollup/dist/rollup.js:6903:51)
    at MagicString$1.overwrite (/Users/grudy/dev/stable/jsapp/node_modules/rollup/dist/rollup.js:6716:8)
    at Node.Identifier.render (/Users/grudy/dev/stable/jsapp/node_modules/rollup/dist/rollup.js:14173:22)
    at /Users/grudy/dev/stable/jsapp/node_modules/rollup/dist/rollup.js:13050:56
    at NodeBase.eachChild (/Users/grudy/dev/stable/jsapp/node_modules/rollup/dist/rollup.js:12977:17)
    at NodeBase.render (/Users/grudy/dev/stable/jsapp/node_modules/rollup/dist/rollup.js:13050:14)
    at Node.MemberExpression.render (/Users/grudy/dev/stable/jsapp/node_modules/rollup/dist/rollup.js:15707:33)
    at /Users/grudy/dev/stable/jsapp/node_modules/rollup/dist/rollup.js:13050:56
    at NodeBase.eachChild (/Users/grudy/dev/stable/jsapp/node_modules/rollup/dist/rollup.js:12977:17)
```

when depending on libraries that use the graphql package. I traced it back to the last else of this code:

```
			if ( startsWith( id, PREFIX ) ) {
				const actualId = id.slice( PREFIX.length );
				const name = getName( actualId );

				if (commonjsModules.has( actualId ))
					return `import { __moduleExports } from ${JSON.stringify( actualId )}; export default __moduleExports;`;
				else if (esModulesWithoutDefaultExport.indexOf(actualId) !== -1)
					return `import * as ${name} from ${JSON.stringify( actualId )}; export default ${name};`;
				else
					return `import * as ${name} from ${JSON.stringify( actualId )}; export default ( ${name} && ${name}['default'] ) || ${name};`;
			}
```
The else gets called here, generating the statement that fails to make it through the `render` section (where the MagicString does this work) correctly.

For whatever reason, I get working and non-breaking output if I change the else to the same as the else if block:

 `return `import * as ${name} from ${JSON.stringify( actualId )}; export default ${name};`;`

It seems it is breaking on the `['default']` and I don't know why.

This seems to be causing problems to various folks, including potentially this issue:

https://github.com/rollup/rollup/issues/1859

**Comment by gaberudy** [comment]
This is fixed in newer versions
