### ISSUE TITLE
esm+cjs=failed

### ISSUE THREAD

**Issue by yurayko** [rollup/rollup-plugin-commonjs#324]
I try to make a bundle from vue and N3-components (vue framework).
If I directly select a common js versions for both of them, then all OK.
But if  select 'vue/dist/vue.esm.js' then rollup crashed with stack trace
```
rollup -c
main.js → build.js...
[!] TypeError: Cannot read property 'forEach' of null
TypeError: Cannot read property 'forEach' of null
    at Module.getReexports (/home/yuray/prj/r/node_modules/rollup/dist/rollup.js:13018:31)
    at new NamespaceVariable (/home/yuray/prj/r/node_modules/rollup/dist/rollup.js:12409:79)
    at Module.getOrCreateNamespace (/home/yuray/prj/r/node_modules/rollup/dist/rollup.js:13046:42)
    at Module.traceExport (/home/yuray/prj/r/node_modules/rollup/dist/rollup.js:13117:29)
    at /home/yuray/prj/r/node_modules/rollup/dist/rollup.js:21034:40
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:746:11)
    at startup (internal/bootstrap/node.js:238:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:572:3)
```
[Here test repository](https://github.com/yurayko/rollup-plugin-commonjs-trbl)
Or this a rollup Issue ?

**Comment by lukastaegert** [comment]
Hi @yurayko, from a first look you should definitely use `rollup-plugin-node-resolve` (which resolved the issues for me). However there still seems to be an issue with rollup itself i.e. you should at least be getting  a better error message so please leave this issue open until we got to the bottom of this.

**Comment by lukastaegert** [comment]
Closing it in favour of rollup/rollup#2317

**Comment by guybedford** [comment]
I've improved the error output for this case in rollup/rollup#2334.

Note that changing to `'vue': path.resolve('node_modules/vue/dist/vue.esm.js')` fixes this too.
