### ISSUE TITLE
Proxies for relative modules

### ISSUE THREAD

**Issue by aleclarson** [rollup/rollup-plugin-commonjs#326]
I'm debugging an issue with relative modules, and I have a quick question:

Are proxies of relative modules supposed to contain a relative path? (eg: `\0commonjs-proxy:./foo`)

Or is the relative path supposed to be resolved by [`node-resolve`](https://github.com/rollup/rollup-plugin-node-resolve/blob/v3.3.0/src/index.js) first?

I'm experiencing an issue where `node-resolve` has its `resolveId` function called with a relative path for its `importer` argument. As far as I can tell, that doesn't work too well.

```
[!] Error: Could not resolve './foo' from commonjs-proxy:./foo
Error: Could not resolve './foo' from commonjs-proxy:./foo
    at error (./node_modules/rollup/dist/rollup.js:3356:15)
    at ./node_modules/rollup/dist/rollup.js:21203:25
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:746:11)
    at startup (internal/bootstrap/node.js:238:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:572:3)
```

Don't worry about solving my issue. I'm looking into it, but I'll need some pointers (starting with the question above). :)

A quick reply would be very appreciated! ❤️

**Comment by aleclarson** [comment]
[This test](https://github.com/rollup/rollup-plugin-commonjs/blob/master/test/form/multiple-var-declarations/output.js#L3-L4) says this is expected. Must be an issue with `node-resolve`.
