### ISSUE TITLE
str.slice is not a function when using experimentalCodeSplitting and the input is an object

### ISSUE THREAD

**Issue by Couto** [rollup/rollup-plugin-commonjs#334]
According to [Rollup's documentation][] is possible to pass an object of named entry points to the input property if we enable the `experimentalCodeSplitting`.

However, this seems to break whenever the `commonjs` plugin is being used:

```
TypeError: str.slice is not a function
    at startsWith (node_modules/rollup-plugin-commonjs/dist/rollup-plugin-commonjs.cjs.js:633:13)
    at resolveId (node_modules/rollup-plugin-commonjs/dist/rollup-plugin-commonjs.cjs.js:675:23)
    at node_modules/rollup-plugin-commonjs/dist/rollup-plugin-commonjs.cjs.js:763:49
    at Array.map (<anonymous>)
    at Object.options (node_modules/rollup-plugin-commonjs/dist/rollup-plugin-commonjs.cjs.js:763:18)
    at applyOptionHook (node_modules/rollup/dist/rollup.js:22009:23)
    at Array.reduce (<anonymous>)
    at getInputOptions$1 (node_modules/rollup/dist/rollup.js:22032:41)
    at Object.rollup (node_modules/rollup/dist/rollup.js:22093:30)
    at build (node_modules/rollup/bin/rollup:1151:19)

error Command failed with exit code 1.
```

Theres a small demo of this problem in the following [gist][] to demonstrate the problem.

[Rollup's documentation]: https://rollupjs.org/guide/en#core-functionality
[gist]: https://gist.github.com/Couto/1075553d0a35cc61ae564ef016dde6b3

**Comment by Couto** [comment]
Closing this issue in favour of #329
