### ISSUE TITLE
Cannot bundle some UMD modules (fastdom)

### ISSUE THREAD

**Issue by piuccio** [rollup/rollup-plugin-commonjs#81]
[fastdom](https://github.com/wilsonpage/fastdom) code looks like this

```js
!(function(win) {

function FastDom() {
   // ...things here
}

// There should never be more than
// one instance of `FastDom` in an app
var exports = win.fastdom = (win.fastdom || new FastDom()); // jshint ignore:line

// Expose to CJS & AMD
if ((typeof define)[0] == 'f') define(function() { return exports; });
else if ((typeof module)[0] == 'o') module.exports = exports;

})(this);
```

Create a page using it

_index.js_
```js
import fastdom from 'fastdom';

fastdom.wite(() => { console.log('done') });
```

### 'import' and 'export' may only appear at the top level

_rollup.config.js_
```js
const babel = require('rollup-plugin-babel');
const commonjs = require('rollup-plugin-commonjs');
const nodeResolve = require('rollup-plugin-node-resolve');

module.exports = {
    entry: 'src/index.js',
    plugins: [
        babel(),
        nodeResolve({
            jsnext: true,
            main: true,
            preferBuiltins: true
        }),
        commonjs()
    ]
};
```

This configuration errors with the message
```
Error parsing node_modules/fastdom/fastdom.js:
'import' and 'export' may only appear at the top level (249:0) in node_modules/fastdom/fastdom.js
```

### does not export default

_rollup.config.js_
```js
const babel = require('rollup-plugin-babel');
const commonjs = require('rollup-plugin-commonjs');
const nodeResolve = require('rollup-plugin-node-resolve');

module.exports = {
    entry: 'src/index.js',
    plugins: [
        babel(),
        nodeResolve({
            jsnext: true,
            main: true,
            preferBuiltins: true
        }),
        commonjs({
            exclude: ['node_modules/fastdom/**']
        })
    ]
};
```

Excluding `fastdom` from `commonjs` results in

```
The `this` keyword is equivalent to `undefined` at the top level of an ES module, and has been rewritten
Module node_modules/fastdom/fastdom.js does not export default (imported by index.js)
Error: Module node_modules/fastdom/fastdom.js does not export default (imported by index.js)
    at Module.trace (node_modules/rollup/src/Module.js:676:30)
    at node_modules/rollup/src/Module.js:264:30
    at Array.forEach (native)
    at node_modules/rollup/src/Module.js:262:25
    at Array.forEach (native)
    at Module.bindReferences (node_modules/rollup/src/Module.js:255:19)
    at node_modules/rollup/src/Bundle.js:101:44
    at Array.forEach (native)
    at node_modules/rollup/src/Bundle.js:101:18
```

Is there a way to include that file without having to rewrite it?

**Comment by TrySound** [comment]
@piuccio Hi. First variant without babel works fine. Didn't try with it, but you may try to exclude node_modules from babel. And make sure you use the latest versions of modules.

**Comment by piuccio** [comment]
@TrySound thanks

I tried excluding both in `commonjs` and `babel` and it didn't work. The only combination I didn't try is the correct one

```js
const babel = require('rollup-plugin-babel');
const commonjs = require('rollup-plugin-commonjs');
const nodeResolve = require('rollup-plugin-node-resolve');

module.exports = {
    entry: 'src/index.js',
    plugins: [
        babel({
            exclude: ['node_modules/fastdom/**']
        }),
        nodeResolve({
            jsnext: true,
            main: true,
            preferBuiltins: true
        }),
        commonjs()
    ]
};
```

Allow me one rant, I find `rollup`'s idea extremely good, but using it is a real pain. Most of the time you're left clueless trying combinations of plugins, sometime even changing the order matters.

Anyway, thanks

**Comment by TrySound** [comment]
Ideally commonjs shouldn't be used. Transpillers are excluded because shared modules already should be transpiller. But in this case there's something weird. Did you try [buble](https://gitlab.com/Rich-Harris/buble)?

**Comment by piuccio** [comment]
I already feel like rollup is bleeding edge, `buble` feels even more so. I don't want to be too early an adopter when it comes to production code.
